var inbox = angular.module('inbox', []);
	
inbox.controller('InboxCtrl', function($scope){
	$scope.messages = [
  "ad duis quis Lorem duis",
  "veniam eu adipisicing tempor veniam",
  "tempor velit voluptate eiusmod non",
  "duis proident adipisicing occaecat fugiat",
  "ipsum officia nulla quis nisi",
  "deserunt consectetur irure labore ea",
  "non pariatur commodo ipsum veniam",
  "nulla deserunt elit nulla dolore",
  "tempor voluptate eu excepteur aliqua",
  "sunt mollit adipisicing magna elit",
  "ea qui Lorem sit ut",
  "exercitation nostrud officia Lorem consequat",
  "laborum qui Lorem consequat do",
  "eiusmod fugiat fugiat dolor officia",
  "laborum et proident id consectetur",
  "quis ut cillum incididunt occaecat",
  "dolore incididunt minim ex do",
  "amet labore pariatur reprehenderit sint",
  "tempor labore quis labore consequat",
  "cupidatat eu adipisicing Lorem amet",
  "elit proident amet elit tempor",
  "quis aute Lorem irure deserunt",
  "ex ex nisi nisi aliqua",
  "commodo reprehenderit nostrud excepteur labore",
  "Lorem in incididunt deserunt velit",
  "nisi aliquip enim est ipsum",
  "excepteur duis minim mollit in",
  "id aliqua nulla nisi irure",
  "non ipsum do nulla pariatur",
  "non duis deserunt ad enim",
  "ut velit quis officia id",
  "sunt enim qui ea aliquip",
  "voluptate eiusmod est irure eu",
  "commodo minim ex laboris sint",
  "esse nostrud incididunt tempor id",
  "Lorem duis occaecat reprehenderit enim",
  "magna laboris sint cupidatat reprehenderit",
  "fugiat fugiat adipisicing consequat elit",
  "ea velit Lorem aliqua ut",
  "sunt exercitation voluptate et ut",
  "qui est laborum ex consectetur",
  "deserunt officia fugiat laborum est",
  "consequat et aliqua consectetur laborum",
  "commodo eu mollit laboris et"
];
});